services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: app-automation-subsiditepatlpg
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - .:/var/www
      - ./scripts:/var/www/scripts
      - scripts_node_modules:/var/www/scripts/node_modules
    networks:
      - app
      - proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - redis

  postgres:
    image: pgvector/pgvector:pg15
    container_name: app-postgres-automation-subsiditepatlpg
    restart: unless-stopped
    environment:
      POSTGRES_DB: automation_subsiditepatlpg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5533:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app

  redis:
    image: redis:alpine
    container_name: app-redis-automation-subsiditepatlpg
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - app

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-automation-subsiditepatlpg
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: sultanmaulachamzah@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "Sult@n354"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app
      - proxy
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin_data:
  scripts_node_modules:

networks:
  app:
    driver: bridge
  proxy:
    external: true
